### ISSUE TITLE
How to protect schema endpoints by "roles" or "member groups"?

### ISSUE THREAD

**Issue by biapar** [nikcio/Nikcio.UHeadless#104]
How to protect schema endpoints by "roles" or "member groups"?

**Comment by nikcio** [comment]
Please clarify what you mean by schema endpoints.

**Comment by biapar** [comment]
For example: a query on some items is possible only for some groups or members.

**Comment by nikcio** [comment]
There's a discription here on how the authorize attribute works: https://chillicream.com/docs/hotchocolate/v12/security/authorization

And then you can refer to the description I gave in #83 on how to use the attribute with the package.
