### ISSUE TITLE
How to query only own data?

### ISSUE THREAD

**Issue by biapar** [nikcio/Nikcio.UHeadless#105]
How to query only own data? That is. I've authenticate the user by Oauth2 and then he can only query his data ( nodes ).

**Comment by nikcio** [comment]
Like querying by the starting nodes of a user?

**Comment by biapar** [comment]
Sorry, I mean member as user. Yes but you can query data of someone else if you change the node id and you are not authorized to do ( thinking to privacy )

**Comment by nikcio** [comment]
I can't think of a way using the core feature set as it is right now but you could check the members access yourself by adding a check in the overridden method where you've added the `[Authorize]` attribute. But if you want real separation of the data you might also have to restrict access to the `Parent` and `Children` properties because you could use these to traverse the content tree, thereby, accessing data unrestricted. To restrict access to the properties you can also use the `[Authorize]` on the properties by creating a custom model extending the basic model in UHeadless. (See the documentation).

If you figure out a way to do it feel free to add a PR with documentation on how to do it or better yet a PR to add it to the core functionality 😄

**Comment by biapar** [comment]
Thanks to your reply. I'm thinking how to do this. Is't possible to use the "member group" permission? That is: If on node there is a group restriction we can check if the user/member is in that group or not.

```csharp
IContent content = base.Services.ContentService.GetById(item.Id);
PublicAccessEntry entry = base.Services.PublicAccessService.GetEntryForContent(content);
if (entry != null)
{
    foreach (var r in entry.Rules)
    {
        if (Roles.IsUserInRole(r.RuleValue))
        {
            "IS AUTHORIZED"
        }
    }
}
else
{
     
}
```

**Comment by biapar** [comment]
<img width="820" alt="image" src="https://user-images.githubusercontent.com/661517/205433080-53d43a0c-04b9-443c-b7eb-974db17f42d1.png">

**Comment by nikcio** [comment]
@biapar I don't think your solution is that far off. But if we wanted to use it as an attribute there are a few things that would need to be solved:

- How do we get the content id for the content node being loaded
- How do we get the member id
- What about pages not accessible to the member. Here you want to either redirect to the login or access denied page.

**Note: If we should add this into UHeadless as the project is right now we need to support developers either not using the Member package and/or developers not using the authorize attribute.**

**Comment by biapar** [comment]
Hi, I created a custom controller that release a oauth2 token with some claims like Member ID and Groups Members as roles. 

I setted the access to to the content node with the member group associated to the login.

So the next step is to customize the authorize by roles or to build a custom controller that check if the requested node has the member roles eguals to the member roles associated to the login.

Please, Could you explain better the note paragraph?

**Comment by biapar** [comment]
Meantime, I create a controller Umbraco API protected by 	`[UmbracoMemberAuthorize("", "Socio Ordinario Group", "")]` and I check if the content node has a rules that contains the member group of the user connected.
I tried:

- login by OAUTH2
- Then call controller
```csharp
private async Task<Boolean> IsAuthorizedToSeeData(Guid id)
		{
			var content = _contentService.GetById(id);
			var entry = _publicAccessService.GetEntryForContent(content);
			var m = await _memberManager.GetCurrentMemberAsync();
			var groups = await _memberManager.GetRolesAsync(m);

			if (entry != null)
			{
				var rulesListContainMe = entry.Rules;

				foreach (var item in rulesListContainMe)
				{

					if (groups.Contains(item.RuleValue))
					{
						return true;
					}
				}

				return false;

			}
			else
			{
				return false;
			}
		}


[UmbracoMemberAuthorize("", "Socio Ordinario Group", "")]
		[ActionName("cont")]
		[HttpGet]
		public async Task<IActionResult> Get(Guid id)
		{
			var content = _contentService.GetById(id);

			 
		var flag = await IsAuthorizedToSeeData(id);
			if (flag)
			{
				return Ok(content);
			}
			else
				return Unauthorized();

		}

```

**Comment by biapar** [comment]
If I understand, we need to build a generic mutation classes and customize the authorize plus to build a custom policies.

**Comment by nikcio** [comment]
This can now be done with the Public Access example where you validate data access on the FE or by extending the models or queries with the authentication logic: https://github.com/nikcio/Nikcio.UHeadless/tree/contrib/examples/code-examples/Headless/PublicAccessExample
