### ISSUE TITLE
Querying all descendants of a node including nested descendants

### ISSUE THREAD

**Issue by louisjrdev** [nikcio/Nikcio.UHeadless#144]
Hello, 

I was wondering if you have a way of querying for all nodes descended from a node e.g. the root node. I am trying to understand how I could build my navigation tree structure using this package. Is it possible?

Thanks

**Comment by louisjrdev** [comment]
Aha, figured it out, nested calls to children{ } looks like it will do the trick

**Comment by nikcio** [comment]
Hey @louisjrdev 

Glad you found a solution!

You could also use something like the `contentDescendantsByGuid` query or similar maybe.

There's also the possibility to make a custom property that creates your navigation information 😉
