### ISSUE TITLE
Empty value when property is shared between cultures

### ISSUE THREAD

**Issue by mrtrandinhvn** [nikcio/Nikcio.UHeadless#145]
### Background
I have a very simple demo umbraco site with these packages installed:
- `<PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="68.2.0.9" />`
- `<PackageReference Include="uSync" Version="11.1.0" />`
- `<PackageReference Include="Nikcio.UHeadless" Version="3.3.0" />`
- `<PackageReference Include="Umbraco.Cms" Version="11.3.1" />`

### Steps to reproduce:
- Create a site with two languages.
- Create a Document type with "Allow vary by culture" **ON**.
- Create a textbox property with "Allow vary by culture" **OFF**.
- Go query for that page with one culture: 
```
{
  contentById(id: 1061, culture: "en-us") {
    id
    properties {
      alias
      editorAlias
      value {
        ... on CustomPropertyValue {
          value # Value of that property will be ""
        }
      }
    }
  }
}
```
### Solution
I suspect that the root cause is because you always add Culture when querying for property value. When the correct way to do that (in Umbraco 11) is adding a simple check like this.
```csharp
public class CustomPropertyValue : BasicPropertyValue
    {
        [GraphQLType(typeof(AnyType))]
        public override object? Value { get; set; }

        public CustomPropertyValue(CreatePropertyValue createPropertyValue) : base(createPropertyValue)
        {
            var property = createPropertyValue.Property;
            Value = property.GetValue(property.PropertyType.Variations == ContentVariation.Culture
                ? createPropertyValue.Culture : string.Empty);
        }
    }
```
As you can see there will be issues with when "Allow segmentation" involves in, but I'm not experienced enough with Umbraco to think about that right now.
### Few words
This project is a game changer for headless cms umbraco. I would love to create a PR but I'm not sure which branch should I fork and create a PR to.
Thank you for your hard work.

**Comment by nikcio** [comment]
Thank you for the issue report. Feel free to make a PR for the v3/contrib branch.😉

**Comment by nikcio** [comment]
There's a few things that needed to be changed for the culture to work properly with the property values. #147 addresses this but includes multiple breaking changes that need to go with it to give a nice developer experience. Therefore this fix will first come in V4 which is still in the works.

**Comment by nikcio** [comment]
I'm closing this issue as the fix will be available in v4 and a preview release has now been released. 😄
