### ISSUE TITLE
Doubt about PropertyValueFilterInput

### ISSUE THREAD

**Issue by PriscilaSS** [nikcio/Nikcio.UHeadless#275]
### Question

Hi! I need help to return all the contents by a search criteria. 

I noticed a where clause that is a PropertyValueFilterInput in some queries. Am I able to use it to look for values inside one or more properties with specific alias, even properties inside blocklists, using fuzzy search?

If not how can I proceed to achieve this?

Thank you in advance.

![image](https://github.com/nikcio/Nikcio.UHeadless/assets/67551246/42c5d681-4c48-41bd-a630-2bf45a3ab182)

**Comment by nikcio** [comment]
Hi @PriscilaSS 

I havn't tried using the filtering for searching in the content from Umbraco. I think a search engine like Examine would be a better fit for a use case like this.

I don't think the filtering supports fuzzy search in the way to make the content searchable like a true search engine would. But anyway the filtering is based on the implementation from HotChocolate: https://chillicream.com/docs/hotchocolate/v13/fetching-data/filtering#and--or-filter
You can see how it works and how to extend the filtering with custom fields so you might be able to find a solution.

**Comment by PriscilaSS** [comment]
Hi! I used the search engine Examine, thank you.
