### ISSUE TITLE
Extend an existing property value does not override a default Basic value

### ISSUE THREAD

**Issue by PriscilaSS** [nikcio/Nikcio.UHeadless#276]
### Question

Hi! I followed this tutorial [Extend an existing property value](https://nikcio.github.io/Nikcio.UHeadless/v3/propertyvalues/extendexistingsimple/)

But I noticed that both Custom and Basic appears together, I thought Basic would be overrided by Custom. Is there a way to allow only Custom to be used?

![image](https://github.com/nikcio/Nikcio.UHeadless/assets/67551246/b4518d81-2976-4179-beb2-66cb761081c5)

**Comment by nikcio** [comment]
Hi

The `BasicRichText` type is also used for the markdown editor. If you want to remove it from your schema you can also overwrite that mapping with your custom model too.
<img width="554" alt="image" src="https://github.com/nikcio/Nikcio.UHeadless/assets/24605285/05cfaf26-94a2-4156-b49e-53647c2f3d36">

**Comment by PriscilaSS** [comment]
Hi

Even when I try to overwrite all the mappings for BasicRichText and BasicContentPicker it still appears on the schema. This is the code where I register the model:
![image](https://github.com/nikcio/Nikcio.UHeadless/assets/67551246/48eb567f-7aec-4ed8-9ea8-cf86d1bc7e33)

**Comment by nikcio** [comment]
Hmm... When I try that locally the `BasicRichText` disappears. Can you find it if you go to `/graphql` and look at the schema definition?
<img width="339" alt="image" src="https://github.com/nikcio/Nikcio.UHeadless/assets/24605285/b130fd1e-f3bd-42bf-ad6f-e5265813264e">

**Comment by PriscilaSS** [comment]
Yes I found it, I am sending the prints for BasicRichText and BasicContentPicker and their Custom.

![image](https://github.com/nikcio/Nikcio.UHeadless/assets/67551246/20dd2c18-2a07-4b26-8b72-b18fdae150dd)
![image](https://github.com/nikcio/Nikcio.UHeadless/assets/67551246/4e2bd361-3c67-449d-ba0b-7f311f3904d2)
![image](https://github.com/nikcio/Nikcio.UHeadless/assets/67551246/70a035a8-1c81-434b-9b3c-4d588d2288ff)
![image](https://github.com/nikcio/Nikcio.UHeadless/assets/67551246/204cfba0-ed48-47c1-97b1-78faf3b28463)

**Comment by nikcio** [comment]
What specific version are you using?

**Comment by PriscilaSS** [comment]
3.3.1

**Comment by nikcio** [comment]
Oh that's properly why then. You are most likey missing a bug fix that came in 4.1.0: https://github.com/nikcio/Nikcio.UHeadless/releases/tag/v4.1.0

https://github.com/nikcio/Nikcio.UHeadless/commit/6f7d43ca16d8216b556dc79d335d16250dc49f57

**Comment by PriscilaSS** [comment]
I understand, I can't change the version to 4.1.0 now due to the version of umbraco we are using. We are thinking about changing, but later. Is there a workaround to achieve this fix in v3.3.1?

**Comment by nikcio** [comment]
You might be able to remove it manually with the UHeadless `GraphQLExtensions` (in the options) as this runs after the defaults are added. But haven't tried that before.

But having both isn't really a problem is it?

**Comment by PriscilaSS** [comment]
It's not a problem, just aesthetic.
Thanks.
