### ISSUE TITLE
Filter By Custom Property Value

### ISSUE THREAD

**Issue by chiragsolanki87111** [nikcio/Nikcio.UHeadless#286]
### Question

Hi,

I want to filter the nodes based on the custom property value. In the following GraphQL query, I have a custom property called "Header". I want to fetch the nodes where the "Header" property has the value "SOME VALUE". How can I achieve this? I have already reviewed the documentation at https://nikcio.github.io/Nikcio.UHeadless/.

{
  contentAll{
    nodes {
     
      namedProperties {
        ... on MediaCoverage {
          header {
            value
          }
        }
      }
    }
  }
}

**Comment by nikcio** [comment]
Hi

I havn't got the time right now to make a full example. But UHeadless uses HotChocolate under the hood and includes the default filtering options from that. You can see an example of a query here https://chillicream.com/docs/hotchocolate/v13/fetching-data/filtering#and--or-filter

You can discover the options at the /graphql UI in your application.

**Comment by chiragsolanki87111** [comment]
Hi @nikcio,

Thank you for your prompt response and for providing the link to the documentation. I appreciate the guidance.

I followed the steps outlined in the provided link, but unfortunately, I'm still encountering difficulties with filtering data using custom properties in my Umbraco project. Despite my efforts, I haven't been able to achieve the desired outcome.

When attempting to implement the filtering, I encountered "The specified input object field `title` does not exist.". This led me to believe that the solution provided in the documentation might not be directly applicable to the Umbraco environment or might require additional configuration specific to Umbraco.

Could you please provide further assistance or guidance on how to address this issue within the context of an Umbraco project?

Thank you for your support.


![image](https://github.com/nikcio/Nikcio.UHeadless/assets/49196606/2c014d4a-d607-4f64-aa42-c3af2dd9daed)

**Comment by nikcio** [comment]
@chiragsolanki87111 Isn't `title` inside `namedProperties`? So it would be something like `{namedProperties:{title: {....}}}`?

**Comment by chiragsolanki87111** [comment]
Hi @nikcio 

I've double-checked the filter conditions, and unfortunately, there is no "namedProperties" available within the filter structure. I've attempted to use "properties" as an alternative, but haven't had any success in filtering by the "title" property.

Could you please provide further guidance on how to structure the filter condition without relying on "namedProperties"? Any additional insights or examples would be greatly appreciated.

Thank you for your assistance.

![image](https://github.com/nikcio/Nikcio.UHeadless/assets/49196606/2a0fdd78-3c7b-4b5b-90cb-e13e601705e8)

**Comment by chiragsolanki87111** [comment]
HI @nikcio

I'm still stuck with the filtering issue and eagerly await your response. Any further guidance would be appreciated.

**Comment by nikcio** [comment]
I don't know that much about filtering on properties. I think you would be better off making your own query type and then making the filter in code.

You can look through the source code on how to create a custom query. For example :

https://github.com/nikcio/Nikcio.UHeadless/blob/v4%2Fcontrib/src%2FNikcio.UHeadless.Content%2FBasics%2FQueries%2FBasicContentAllQuery.cs

https://github.com/nikcio/Nikcio.UHeadless/blob/v4%2Fcontrib/src%2FNikcio.UHeadless.Content%2FQueries%2FContentAllQuery.cs

**Comment by chiragsolanki87111** [comment]
Sorry for the late reply.

The above given solution works for me. Thanks :)

**Comment by chiragsolanki87111** [comment]
Sorry for the late reply.

The above given solution works for me. Thanks :)
