### ISSUE TITLE
Unable to obtain children of content within BasicContentPicker

### ISSUE THREAD

**Issue by ollya-puregym** [nikcio/Nikcio.UHeadless#309]
Hi there,

I am currently trying to understand the method of accessing selected nodes from within a content picker. I first noticed that there was no relevant property for me to query the content, which led me to discover that the `Content` property has a tag on it to prevent it being visible within the schema ([see here](https://github.com/nikcio/Nikcio.UHeadless/blob/v4.2.1/src/Nikcio.UHeadless.Base/Base/Basics/EditorsValues/ContentPicker/Models/BasicContentPickerItem.cs#L53)).

I am just curious about the logic behind this decision as I was unable to find any documentation on why that would be the case - as now I am looking to create my own custom BasicContentPickerItem that would get the `children` prop from the `content` prop and register a custom BasicContentPicker alongside.

```
	public sealed class CustomBasicContentPickerItem : BasicContentPickerItem
	{
		/// <summary>
		/// Gets the children of the selected content
		/// </summary>
		[GraphQLDescription("Gets the children of the selected content")]
		public IEnumerable<IPublishedContent> Children => Content.Children;

		public CustomBasicContentPickerItem(CreateContentPickerItem createContentPickerItem) : base(createContentPickerItem)
		{
		}
	}
```
```
	public class CustomBasicContentPicker : BasicContentPicker<CustomBasicContentPickerItem>
	{
		public CustomBasicContentPicker(CreatePropertyValue createPropertyValue, IDependencyReflectorFactory dependencyReflectorFactory, IVariationContextAccessor variationContextAccessor) : base(createPropertyValue, dependencyReflectorFactory, variationContextAccessor)
		{
		}
	}
```

It would be great to know if this is the correct approach to resolving my issue.

Thanks!

P.S Very much enjoying using the package, so far has provided us great route to moving to headless compared to using the Content Delivery API supplied by Umbraco!

**Comment by nikcio** [comment]
Hi @ollya-puregym 

You are totally on the correct path. It is by design that i havn't made every property available out of the box because not every property will be used by everyone and I'm going to make this more clear with version 5 which is currently under development.

But for your use case of getting the children of the selected content you are looking to extend the `BasicContentPickerItem` as this represents a single picked value you can then create a `BasicContentPicker<CustomContentPickerItem>` mapping in the property map. Like it seems you are trying to do.

For getting the children you dont want to use IPublishedContent as the model as this can't be serialized to JSON. Instead you want something like this:

https://github.com/nikcio/Nikcio.UHeadless/blob/3fb9403343beed46bd2d8750777a69879a3d6c44/src/Nikcio.UHeadless.Content/Basics/Models/BasicContent.cs#L158

**Comment by ollya-puregym** [comment]
Hi again @nikcio , thanks for your swift response.

I have gone ahead and made my interpretation of what you gave as an example above within my `CustomBasicContentPickerItem` class.

```
  [GraphQLDescription("Represents a content picker item.")]
  public class CustomBasicContentPickerItem<TContent> : BasicContentPickerItem
  where TContent : IContent
  {
  
  public CustomBasicContentPickerItem(IContentFactory<TContent> contentFactory, CreateContentPickerItem createContentPickerItem) : base(createContentPickerItem)
  {
	  ContentFactory = contentFactory;
  }
  
  /// <summary>
  /// Gets the children of the selected content
  /// </summary>
  [GraphQLDescription("Gets the children of the selected content")]
  public virtual IEnumerable<TContent?>? Children => Content?.ChildrenForAllCultures.Select(child =>
	  ContentFactory.CreateContent(child, Culture, UrlSegment, Fallback.ToDefaultLanguage));
  
  protected virtual IContentFactory<TContent> ContentFactory { get; }
```
And then updated the `CustomBasicContentPicker` class to the following

```
  public class CustomBasicContentPicker : BasicContentPicker<CustomBasicContentPickerItem<IContent>
  {
    public CustomBasicContentPicker(CreatePropertyValue createPropertyValue, IDependencyReflectorFactory dependencyReflectorFactory, IVariationContextAccessor variationContextAccessor) : base(createPropertyValue, dependencyReflectorFactory, variationContextAccessor)
    {
    }
  }
``` 

This seems to be correct to me, however, when I try and spin up my application I get the following error:-
> Interface `IContent` has no fields declared. (HotChocolate.Types.InterfaceType<Nikcio.UHeadless.Content.Models.IContent>)

Is there a different class I should be using instead of `IContent` in the generic class definition of `CustomBasicContentPicker`?

Thanks!

**Comment by nikcio** [comment]
Hi

Try using `BasicContent` instead of `IContent` you need to give it a concrete class for it to work.

**Comment by ollya-puregym** [comment]
> Hi
> 
> Try using `BasicContent` instead of `IContent` you need to give it a concrete class for it to work.

And that was exactly what I was missing, thanks a bunch!

P.S If I could buy you a coffee for your assistance, drop me a link!

**Comment by nikcio** [comment]
@ollya-puregym https://github.com/sponsors/nikcio
