### ISSUE TITLE
Extended Content Model only when requested in the graphQL fields

### ISSUE THREAD

**Issue by PriscilaSS** [nikcio/Nikcio.UHeadless#322]
### Question

Hi, I am extending my content model with custom properties, like this tutorial:
https://nikcio.github.io/Nikcio.UHeadless/v3/content/extendexistingpublicaccess/

I was wondering, is there a way to only perform an action if the field was requested in the graphQL fields? For example, to get the public access settings only if it was requested in the graphQL fields.

**Comment by nikcio** [comment]
@PriscilaSS Yes there is. If you make the property a method then it will only be executed if quried. See the Public access example for v5: https://nikcio.github.io/Nikcio.UHeadless/v5/extending/content/#example-custom-content-model-extending-the-existing-content-model

As long as you dont set the value for a property in the constructor but via the get then it will only be created if requested and the same for methods of that makes sense

**Comment by PriscilaSS** [comment]
Hi! That was very helpfull, thank you so much.
