### ISSUE TITLE
Is it possible add new property?

### ISSUE THREAD

**Issue by andersonrosilva** [nikcio/Nikcio.UHeadless#325]
### Question

In the version 4, the alias property it was replaced with the model property.
Is it possible to create a custom property to add newly?

![image](https://github.com/user-attachments/assets/086b064a-a77b-4547-890e-514976ea6bbd)

**Comment by nikcio** [comment]
Hi @andersonrosilva 

You can always create your own model for an editor see the documentation for this. Do note that you cannot create a universal model extension but need to override all the editor models you want the new property on.

For example if you want the media picker to give an extra property you can override that model and the same for the block list or rich text editor. For all "non-special" editors they will all use the BasicPropertyValue which can be overridden with on the default key. Do remember that this model is the fallback for every editor that doesnt have a specific model registered for it.

The default key is: `PropertyConstants.DefaultKey`

See for example this documentation: https://nikcio.github.io/Nikcio.UHeadless/v4/extending/properties/rich-text/

**Comment by andersonrosilva** [comment]
Hi @nikcio 
Thank you.
