### ISSUE TITLE
How to protect api?

### ISSUE THREAD

**Issue by biapar** [nikcio/Nikcio.UHeadless#329]
### Question

Hi, UaU this package is compatibile with U14.x!
How to protect api and query the protect content? 
Thanks.

**Comment by nikcio** [comment]
https://nikcio.github.io/Nikcio.UHeadless/v5/fundamentals/security/

**Comment by biapar** [comment]
Thanks. That is this bypass the Umbraco content protection. 
Can I use only Graphql? Which are the differences with native Umbraco Delivery Api?

**Comment by nikcio** [comment]
I'm not sure I understand your question. Could you outline the use case?

**Comment by biapar** [comment]
Ok. How to read the content nodes that are protected by Umbraco group or other policy?

**Comment by nikcio** [comment]
You can fetch the content like normal. To get the rights for a content node take a look at the public access example: https://nikcio.github.io/Nikcio.UHeadless/v5/extending/content/#example-extended-the-content-model-with-public-access-settings

Then you would need to filter the data on the client side.

If you want to filter the data inside UHeadless you will need to make a custom query where you filter the content based on something on the request like a header with a token or similar. (Just like a normal API endpoint). You can access the request from the `IResolverContext`. But that will be very custom to your use case and you would need to develop that on your own as there's no out-of-the-box solution for this.

**Comment by biapar** [comment]
I explain better. You know that in Umbraco you can protect some media and content nodes by group or membership and when you try to visit that content from website or delivery contnet Api, Umbraco send you to the member login page. How Do your package work in this case?

**Comment by nikcio** [comment]
That is the case i've explained above. The content will be provided as usual so it is up to the client to filter the data. This can be done by extending the content model so it exposes the public access data. "What configuration is set in Umbraco about permissions". Then your client can filter the data appropriately. If you would rather do it inside UHeadless then you'll need to create a custom query that will filter data based on the request to UHeadless. This could be done with a header that has a token identitying the user that then could be hold against the data coming from the public access data inside Umbraco. See the example i linked.

**Comment by biapar** [comment]
Thanks. So, If I understand...you bypass the security base of Umbraco.

![CleanShot 2024-09-09 at 12 32 11@2x](https://github.com/user-attachments/assets/9d7a67ca-26b4-4f3e-bf05-b21383e66f5d)

**Comment by nikcio** [comment]
Yes you have to expose that part yourself by following the guides I've linked
