### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by PeterKvayt** [nikcio/Nikcio.UHeadless#332]
### Question

Are there any plans to future support of this project?
Are there any plans to release package for umbraco 14 and 15?
As I can see there is version for umbraco 14 but it is in preview for a 3 month.

**Comment by nikcio** [comment]
@PeterKvayt Hey.

Theres a preview version for v14 (v6.0.0) that has been out for a while I havn't heard of any issues with it. So will make a release version after some tests on the latest Umbraco v14. So within this week or the next there should be a version available for that. Then I'll look what is needed for V15.

Thanks for bringing it up. 😁

**Comment by nikcio** [comment]
@PeterKvayt I've now release an update to v5.0.0 (5.1.0) with some dependency updates and a v6.0.0 version that supports v14.

I've looked into v15 but there are some changes to how some things can be resolved that have to be adjusted but I have a 90% working version on v7/contrib

Hope this makes the status of the project clear to you 😄

**Comment by PeterKvayt** [comment]
@nikcio Many thanks for fast reply and for you work!

Now it is clear for me!

Hope our team start working with your package soon and we will bring improvements to your package together!
