### ISSUE TITLE
Allow ParameterType to be IsAssignableFrom()

### ISSUE THREAD

**Issue by gavinharriss** [nikcio/Nikcio.UHeadless#57]
https://github.com/nikcio/Nikcio.UHeadless/blob/b978a4539ae2d1d20f252fbe4a78d3ac93dccaf6/src/Nikcio.UHeadless/Reflection/Factories/DependencyReflectorFactory.cs#L96

Thank you for sharing your code, just what I needed! :)

I did find that I needed to change this line to:

`if (parameters[i].ParameterType != requiredParameter && !parameters[i].ParameterType.IsAssignableFrom(requiredParameter))`

to give it better flexibility for more use cases e.g. for interfaces and inheritance type scenarios.

Figured I'd share back in case it's helpful.

**Comment by nikcio** [comment]
@gavinharriss Thanks for the feedback. This is now part of the package in version 2.2.1
