### ISSUE TITLE
Extending BlockList blocks?

### ISSUE THREAD

**Issue by chris-evansnz** [nikcio/Nikcio.UHeadless#61]
First of all, just wanted to say this package is very exciting - thanks so much for your work on it!

Also, I had a question about extending the Block List editor.

I can see how we can add custom properties to the parent block list property as per here:
https://github.com/nikcio/Nikcio.UHeadless/blob/v2/contrib/docs/v2/propertyValues/extendBlockList.md

But I can't figure out the syntax if we wanted to add a custom property to the child blocks elements themselves, e.g. having a custom property show in each of the "blocks" items underneath the value property of the BlockList.   Is that possible?

**Comment by nikcio** [comment]
Hi @chris-evansnz,

In this case, you want to extend the [BasicBlockListItem](https://github.com/nikcio/Nikcio.UHeadless/blob/v2/contrib/src/Nikcio.UHeadless/UmbracoElements/Properties/EditorsValues/BlockList/Models/BasicBlockListModel.cs) and use this instead of the BasicBlockListItem that is used in the documentation.

![image](https://user-images.githubusercontent.com/24605285/175221089-53fbca97-92f6-434d-b200-2ed99e0edb71.png)


The BasicBlockListModel takes a type of BasicBlockListItem as the generic parameter so you just need to have another class inherit from the BasicBlockListItem eg.

```csharp
public class CustomBlockListItem : BasicBlockListItem<BasicProperty> {

    public string MyCustomProperty { get; set; }

    public CustomBlockListItem (CreateBlockListItem createBlockListItem, IPropertyFactory<BasicProperty> propertyFactory) {
        MyCustomProperty = "Hello I'm Custom!";
    }
}
```

```csharp
public class CustomBlockListModel : BasicBlockListModel<CustomBlockListItem> {

    public string MyCustomProperty { get; set; }

    public CustomBlockListModel(CreatePropertyValue createPropertyValue, IDependencyReflectorFactory dependencyReflectorFactory) : base(createPropertyValue, dependencyReflectorFactory) {
        MyCustomProperty = "Hello I'm Custom!";
    }
}
```

**Comment by nikcio** [comment]
@chris-evansnz Did this answer your question?

**Comment by chris-evansnz** [comment]
@nikcio   thanks so much for the quick response! I live in New Zealand so my time zone is a bit odd - hence the slower reply.

I figured something like this was required. I just tried implementing that, and the code compiles ok but I'm not sure how to query my new property.

I've got this:

```C#
public class CustomBlockListModel : BasicBlockListModel<BasicBlockListItem<BasicProperty>>
{

    public string MyCustomProperty { get; set; }

    public CustomBlockListModel(CreatePropertyValue createPropertyValue, IDependencyReflectorFactory dependencyReflectorFactory) : base(createPropertyValue, dependencyReflectorFactory)
    {
 
        MyCustomProperty = "Hello I'm Custom at parent!";
        
    }
}

public class CustomBlockListItem : BasicBlockListItem<BasicProperty>
{

    public string MyCustomProperty2 { get; set; }

    public CustomBlockListItem(CreateBlockListItem createBlockListItem, IPropertyFactory<BasicProperty> propertyFactory) : base(createBlockListItem, propertyFactory)
    {
        MyCustomProperty2 = "Hello I'm Custom in block item!2";
    }
}
```

And I'm running this graphql query on a page I have called Contact Us:

```GraphQL
{
  contentByAbsoluteRoute (route: "/contact-us") {      
    name,
    id,     
    properties {
      alias,
      value,
      editorAlias,
      __typename      
    }
  }
}
```

I get this response, which shows the first custom property on the parent Block List, but not the second custom property on the block children:

```JSON
{
  "data": {
    "contentByAbsoluteRoute": {
      "name": "Contact us",
      "id": 1070,
      "properties": [
        {
          "alias": "contentBlocks",
          "value": {
            "myCustomProperty": "Hello I'm Custom at parent!",
            "blocks": [
              {
                "contentProperties": [
                  {
                    "alias": "title",
                    "value": {
                      "value": "My test feature"
                    },
                    "editorAlias": "Umbraco.TextBox"
                  },
                  {
                    "alias": "text",
                    "value": {
                      "value": "<p>This is some text for the feature</p>"
                    },
                    "editorAlias": "Umbraco.TinyMCE"
                  },
                  {
                    "alias": "image",
                    "value": {
                      "mediaItems": [
                        {
                          "url": "https://localhost:44387/media/ivmfpss5/90mmplusnailerpluswebplusp1.png",
                          "id": 1069
                        }
                      ]
                    },
                    "editorAlias": "Umbraco.MediaPicker3"
                  },
                  {
                    "alias": "showImageOnRight",
                    "value": {
                      "value": false
                    },
                    "editorAlias": "Umbraco.TrueFalse"
                  }
                ],
                "settingsProperties": [],
                "contentAlias": "featureBlock",
                "settingsAlias": null
              },
              {
                "contentProperties": [
                  {
                    "alias": "title",
                    "value": {
                      "value": "Second feature"
                    },
                    "editorAlias": "Umbraco.TextBox"
                  },
                  {
                    "alias": "text",
                    "value": {
                      "value": "<p>Some text for the second feature</p>"
                    },
                    "editorAlias": "Umbraco.TinyMCE"
                  },
                  {
                    "alias": "image",
                    "value": {
                      "mediaItems": [
                        {
                          "url": "https://localhost:44387/media/b1sgsw1d/_0002_layer-30.png",
                          "id": 1072
                        }
                      ]
                    },
                    "editorAlias": "Umbraco.MediaPicker3"
                  },
                  {
                    "alias": "showImageOnRight",
                    "value": {
                      "value": true
                    },
                    "editorAlias": "Umbraco.TrueFalse"
                  }
                ],
                "settingsProperties": [],
                "contentAlias": "featureBlock",
                "settingsAlias": null
              }
            ]
          },
          "editorAlias": "Umbraco.BlockList",
          "__typename": "BasicProperty"
        }
      ]
    }
  }
}
```

Is there something else I need to do in code to expose this new custom property on the children, or is there something I need to add in the graphql query?  I couldn't see the MyCustomProperty2 in the playground schema docs.

If I try to query it explicity I get this response in the graphql playground:

```
"The field `myCustomProperty2` does not exist on the type `BasicProperty`.",
```

Thanks again for your help!

**Comment by nikcio** [comment]
@chris-evansnz you need to change this line:
```csharp
public class CustomBlockListModel : BasicBlockListModel<BasicBlockListItem<BasicProperty>>
```

To this

```csharp
public class CustomBlockListModel : BasicBlockListModel<CustomBlockListItem<BasicProperty>> 

```

Otherwise you don't use your custom implementation of the block list item.

About the properties not being available in the GraphQL playground. This will be fixed in version 3. Right now it's just a normal JSON text that's put into the property hence why you can't specifically query the properties value.

**Comment by chris-evansnz** [comment]
Hmm - when I try that I get this compilation error:

![image](https://user-images.githubusercontent.com/58791033/175755974-a1eab10c-3213-4985-bc2f-76d234d9c3ac.png)

is there something else I need to include or declare?

**Comment by nikcio** [comment]
Oh sorry @chris-evansnz. It needs to say:

```csharp
public class CustomBlockListModel : BasicBlockListModel<CustomBlockListItem> 
```

Your `CustomBlockListItem` isn't generic and therefore doesn't take an type argument eg. `<BasicProperty>`

**Comment by chris-evansnz** [comment]
Ah yes, that makes sense.  I can see the property in the results now, thanks so much for your responses! 

Will keep experimenting with this package and see how we can make use of it in our projects, it's very promising indeed.
