### ISSUE TITLE
How do you write a query to pull back data for all properties? (Breaking Change 2.0 -> 3.0)

### ISSUE THREAD

**Issue by markadrake** [nikcio/Nikcio.UHeadless#75]
Prior to 3.0, I could get all of the property data back.

```
{
  contentByAbsoluteRoute (route: "/") {
    name,
    url
    key,
    id,
    properties {
      alias,
      value
    }
  }
}

```

_I'm aware this is a breaking change._ 

Now I'm required to extrapolate this generic object across 10 types: `BasicBlockListModel`, `BasicContentPicker`, `BasicDateTimePicker`, `BasicLabel`, `BasicMediaPicker`, `BasicMemberPicker`, `BasicMultiUrlPicker`, `BasicNestedContent`, `BasicPropertyValue`, `BasicRichText`.
 
So I thought, let's use a **fragment**...

```
{
  contentByAbsoluteRoute (route: "/") {
    name,
    url
    key,
    id,
    properties {
      value {
        ... propertyValue
      }
    }
  }
}

```

The fragment approach works well until you come across `BasicBlockListModel` or `BasicNestedContent`. These models have content inside them, but I'm not allowed to call a fragment recursively.

```
fragment propertyValue on PropertyValue {
  alias,
  ... on BasicBlockListModel {
    blocks {
      contentAlias,
      contentProperties {
        ... propertyValue        
      },
      settingsAlias,
      settingsProperties {
        ... propertyValue        
      }
    }
  }
}
```

I understand this is a breaking change but is it still possible to **ask for all property data** in my query?

**Comment by nikcio** [comment]
Hi @markadrake 

Unfortunately to my understanding the GraphQL spec doesn't allow for infinite recursion you can read more here: https://github.com/graphql/graphql-spec/issues/91#issuecomment-254895093

But there's atleast two ways to workaround this issue:

1. If you like the old way of requesting data better you can overrride it. See an example of how to do it here: https://github.com/nikcio/Nikcio.UHeadless/commit/d5d26101e5c7c9cb65def2a57aa93e061be3ad53
<img width="918" alt="image" src="https://user-images.githubusercontent.com/24605285/189141947-8160dc33-7fe4-4d88-a94d-ac8dd2aaa6be.png">

2. If you'd like to preserve the current way of querying you will have to manually nest the amount of levels deep you want to go into a block list. Let's say you for example don't use more than 3 levels deep nested block lists then you could do something like this:
```graphql
{
  contentAtRoot {
    nodes {
      properties {
        value {
          ...propertyValues
        }
      }
    }
  }
}

fragment propertyValues on PropertyValue {
  ...allValues
  ... on BasicBlockListModel {
    blocks {
      contentProperties {
        value {
          ...allValues
          ... on BasicBlockListModel {
            blocks {
              contentProperties {
                value {
                  ...allValues
                  ... on BasicBlockListModel {
                    blocks {
                      contentProperties {
                        value {
                          ...allValues
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

fragment allValues on PropertyValue {
  ...basicValue
  ...contentPicker
  ...label
}

fragment contentPicker on PropertyValue {
  ... on BasicContentPicker {
    contentList {
      id
    }
  }
}

fragment basicValue on PropertyValue {
  ... on BasicPropertyValue {
    value
  }
}

fragment label on PropertyValue {
  ... on BasicLabel {
    label: value
  }
}
```

By keeping within the GraphQL spec you still have all the features that GraphQL brings. For example here I've set a label value to be aliased as label.

I hope this answers your question.
