### ISSUE TITLE
How mean this?

### ISSUE THREAD

**Issue by biapar** [nikcio/Nikcio.UHeadless#84]
![image](https://user-images.githubusercontent.com/661517/192252853-9771e9c1-f8e4-4bc6-a626-d91875d271cc.png)

**Comment by nikcio** [comment]
@biapar UHeadless is built with the Hot Chocolate framework which bundles their GUI for querying the endpoint called Banana Pop Cake. You can read more about it here: https://chillicream.com/docs/bananacakepop

You don't have to sign into anything to test the endpoint and it will save every document you create in the browser as long as you haven't signed in. It works very much like [Postman](https://www.postman.com/)

**Side note: You don't have to use the included GUI to query the endpoint you can use [Postman](https://www.postman.com/) or something more integrated with GraphQL like [Apollo studio](https://www.apollographql.com/docs/studio/)**
