### ISSUE TITLE
Is't possibile to push data to the Umbraco or only read from it?

### ISSUE THREAD

**Issue by biapar** [nikcio/Nikcio.UHeadless#87]
Is't possibile to push data to the Umbraco or only read from it?

**Comment by nikcio** [comment]
At this moment UHeadless only supports reading data, though it is possible to create your own mutations on top of the existing framework. See: https://chillicream.com/docs/hotchocolate/defining-a-schema/mutations

Every time you see this in to documentation you just need to add it to the `UHeadlessGraphQLOptions` --> `GraphQLExtensions` section of the UHeadless options. Here the IRequestExecutorBuilder is exposed.

```csharp
services
    .AddGraphQLServer()
    .AddDefaultTransactionScopeHandler();
```

Example:

```csharp
services.AddUmbraco(_env, _config)
                .AddBackOffice()
                .AddWebsite()
                .AddComposers()
                .AddUHeadless(new()
                {
                    UHeadlessGraphQLOptions = new()
                    {
                        GraphQLExtensions = (IRequestExecutorBuilder builder) =>
                        {
                            builder.AddDefaultTransactionScopeHandler()
                            return builder;
                        },
                    },
                })
                .Build();
```

**Note: Do not include `.AddGraphQLServer()` this is already added to the builder**
